version: '3.3'
services:
  backend:
    build: ./backend
  frontend:
    build: 
      context: ./frontend
      args: 
        FRONTEND_ENV: development

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always